In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

In [7]:
np.concatenate((arr1, arr2, arr3)).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.vstack((arr1, arr2, arr3))  # 세로로 쌓을 땐
np.hstack((arr1, arr2, arr3))  # 가로로 쌓을 땐

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, -1, 2])

v1+v2

array([5, 1, 5])

In [16]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, -1, 2])

v1@v2
np.dot(v1, v2)
np.matmul(v1, v2)

8

In [17]:
arr1 = np.array([1, 2, 3])

arr1 + 3

array([4, 5, 6])

In [18]:
## Broadcasting
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v1 = np.array([-1, -2, -3])

mat1 + v1

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [30]:
img = np.random.random((5, 5))

img.reshape(25, )
img.ravel()
img.flatten()
img.shape

(5, 5)

In [33]:
N = int(input("N? : ")) # 사용자 입력으로 받은 자연수 N
data = np.random.random((N, 6)) # N x 6 matrix

data.flatten()
data.ravel()
data.reshape(-1, )

N? : 6


array([0.60186682, 0.831986  , 0.28155183, 0.67684365, 0.24743264,
       0.92362716, 0.47380246, 0.23856066, 0.49311362, 0.82838611,
       0.19220302, 0.69190254, 0.16884065, 0.6053651 , 0.35369005,
       0.97775803, 0.564978  , 0.40592463, 0.56290326, 0.76046283,
       0.96753429, 0.14912643, 0.76554121, 0.08296621, 0.57045233,
       0.56463798, 0.13928785, 0.81688311, 0.13936789, 0.42098471,
       0.76097457, 0.26303017, 0.51699871, 0.42787681, 0.68090861,
       0.30983677])

In [45]:
# x = int(input("Number? : "))
x = 10

def trigonometry(x):
    print("sim({}) : {}".format(x, round(np.sin(x), 4)))
    print("cos({}) : {}".format(x, round(np.cos(x), 4)))
    print("tan({}) : {}".format(x, round(np.tan(x), 4)))
    return None

trigonometry(10)

print(f"{np.sin(10):.4f}")

sim(10) : -0.544
cos(10) : -0.8391
tan(10) : 0.6484
-0.5440


In [51]:
x = 3.14

print(f"abs({x}) : {np.abs(x):.4f}")
print(f"root({x}) : {np.sqrt(x):.4f}")
print(f"square({x}) : {np.square(x):.4f}")

abs(3.14) : 3.1400
root(3.14) : 1.7720
square(3.14) : 9.8596


In [54]:
# x = np.abs(float(input("Number? : ")))
x = 3.14

print(f"exp({x}) : {np.exp(x):.4f}")
print(f"log({x}) : {np.log10(x):.4f}")

Number? : 25.67
exp(25.67) : 140714661553.7538
log(25.67) : 1.4094


In [58]:
arr = np.array([1, -5, 3.4, 55.41, -1009, 2245, -575, -1935.124])

arr.sort()
np.sort(arr)

array([-1.935124e+03, -1.009000e+03, -5.750000e+02, -5.000000e+00,
        1.000000e+00,  3.400000e+00,  5.541000e+01,  2.245000e+03])

In [60]:
arr = np.array([1, -5, 3.4, 55.41, -1009, 2245, -575, -1935.124])

print(np.argsort(arr))

[7 4 6 1 0 2 3 5]


In [65]:
mat = np.array([[1, -1, 3],
               [4, 3, -6],
               [0, 11, 9]])

np.sort(mat[:,])
print(np.sort(mat, axis = 1)) 



[[-1  1  3]
 [-6  3  4]
 [ 0  9 11]]


In [78]:
mat = np.array([[1, -1, 3],
               [4, 3, -6],
               [0, 11, 9]])

np.sort(mat, axis=0)[::-1]
np.sort(mat, axis=1)[::-1]
-np.sort(-mat, axis=0)

array([[ 4, 11,  9],
       [ 1,  3,  3],
       [ 0, -1, -6]])